# Generated by Django 2.1.5 on 2019-02-16 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('editor', 'Can Add and edit wiki Articles'),)},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articleedit',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
