# Generated by Django 2.1.5 on 2019-02-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_typematchup'),
        ('wiki', '0003_auto_20190216_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.Pokemon'),
        ),
    ]
