# Generated by Django 2.1.5 on 2019-03-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_article_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('editor', 'Can Add and edit wiki Articles'), ('publisher', 'Can Publish wiki Articles'))},
        ),
    ]
