# Generated by Django 2.1.5 on 2019-01-17 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Trainer Name')),
                ('team', models.IntegerField(choices=[(1, 'Mystic'), (2, 'Valor'), (3, 'Instinct')])),
                ('xp', models.BigIntegerField(verbose_name='Total XP')),
                ('pokedex_number', models.IntegerField(verbose_name='Pokedex Entries')),
                ('pokemon_caught', models.IntegerField(verbose_name='Pokemon Caught')),
                ('eggs_hatched', models.IntegerField(verbose_name='Eggs Hatched')),
                ('kilometers_walked', models.FloatField(verbose_name='Kilometers Walked')),
                ('pokestops_spun', models.IntegerField(verbose_name='Pokestops Spun')),
                ('research_tasks', models.IntegerField(verbose_name='Research Tasks')),
                ('ace_trainer', models.IntegerField(verbose_name='Ace Trainer')),
                ('battles_won', models.IntegerField(verbose_name='Battles Won')),
                ('hours_defended', models.IntegerField(verbose_name='Hours Defended')),
                ('berries_fed', models.IntegerField(verbose_name='Berries Fed')),
                ('great_veteran', models.IntegerField(verbose_name='Great League Veteran')),
                ('ultra_veteran', models.IntegerField(verbose_name='Ultra League Veteran')),
                ('master_veteran', models.IntegerField(verbose_name='Master League Veteran')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
