# Generated by Django 2.1.5 on 2019-01-19 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20190119_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMatchup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=4)),
                ('attacking_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attacking_matchups', to='pokemon.Type')),
                ('defending_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='defending_matchups', to='pokemon.Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
